#ifndef STATUS_H
#define STATUS_H

typedef unsigned short FLOC_STATUS;

#define FLOC_STATUS_SUCCESS (0)                                                     
#define FLOC_STATUS_FAILURE (1)                                                     

#define FLOC_STATUS_MEMORY_ALLOC_FAIL (2)                                           
#define FLOC_STATUS_INVALID_HANDLE (3)                                              
#define FLOC_STATUS_DEBUGGER_ALREADY_REGISTERED (4)                                 
#define FLOC_STATUS_DEBUGGER_ATTACH_FAIL (5)                                        
#define FLOC_STATUS_DEBUGGER_NOT_REGISTERED (6)                                     
#define FLOC_STATUS_DEBUGGER_DETACH_FAIL (7)                                        
#define FLOC_STATUS_TARGET_ALREADY_SET (8)                                          
#define FLOC_STATUS_TOO_MANY_CONTEXTS (9)                                           
#define FLOC_STATUS_DEBUG_LOOP_ALREADY_RUNNING (10)                                 
#define FLOC_STATUS_DEBUG_LOOP_ALREADY_STOPPED (11)                                 
#define FLOC_STATUS_FLOC_DEBUG_LOOP_IS_RUNNING (12)                                  
#define FLOC_STATUS_FOREIGN_DEBUGGER_TEST_FAIL (13)                                 
#define FLOC_STATUS_FOREIGN_DEBUGGER_ALREADY_ATTACHED (14)                          
#define FLOC_STATUS_FOREIGN_DEBUGGER_NOT_ATTACHED (15)                              
#define FLOC_STATUS_TARGET_NOT_SET (16)                                             
#define FLOC_STATUS_DEBUG_LOOP_STOP_FAIL (17)                                       
#define FLOC_STATUS_DEBUG_THREAD_START_FAIL (18)                                    
#define FLOC_STATUS_DEBUG_BREAK_FAIL (19)                                           
#define FLOC_STATUS_PROCESS_HANDLE_ACQUIRE_FAIL (20)                                 
#define FLOC_STATUS_STEP_ALREADY_ACTIVE (21)                                        
#define FLOC_STATUS_DEBUG_LOOP_STOPPED (22)                                         
#define FLOC_STATUS_TRACKER_RESET_FAIL (23)                                         
#define FLOC_STATUS_TRACKER_ENABLE_FAIL (24)                                        
#define FLOC_STATUS_STEP_ACTIVE (25)                                                
#define FLOC_STATUS_ENABLING_BREAKPOINT_WITHOUT_DEBUGGING (26)                      
#define FLOC_STATUS_STEP_ALREADY_STOPPED (27)                                       
#define FLOC_STATUS_TRACKER_DISABLE_FAIL (28)                                       
#define FLOC_STATUS_VECTOR_PUSHBACK_FAIL (29)                                       
#define FLOC_STATUS_TRACKER_ALREADY_EXISTS (30)                                     
#define FLOC_STATUS_TRACKER_INVALID_TYPE (31)                                       
#define FLOC_STATUS_MEMORY_READ_FAIL (32)                                           
#define FLOC_STATUS_TRACKER_NOT_FOUND (33)                                          
#define FLOC_STATUS_TRACKER_ENABLED (34)                                            
#define FLOC_STATUS_DEBUG_LOOP_FOREIGN (35)                                         
#define FLOC_STATUS_DEBUGGER_ALREADY_ATTACHED (36)                                  
#define FLOC_STATUS_TARGET_CANNOT_CHECK_DEBUGGER (37)                               
#define FLOC_STATUS_DEBUGGER_NOT_FOUND (38)                                         
#define FLOC_STATUS_DEBUGGER_RUNNING (39)                                           
#define FLOC_STATUS_ILLOGICAL_OVERRIDE (40)                                         
#define FLOC_STATUS_TARGET_DIED (41)                                                
#define FLOC_STATUS_INVALID_TARGET (42)                                             
#define FLOC_STATUS_INSUFFICIENT_PRIVILEGES (43)      
#define FLOC_STATUS_TARGET_NOT_64BIT (44)
#define FLOC_STATUS_HOOK_CREATE_FAIL (45)

#endif /* STATUS_H */
